kind: Service
apiVersion: v1
metadata:
  name: traffic
  labels:
    name: traffic
spec:
  ports: 
     - port: 8080      
       targetPort: 8080  
       protocol: TCP
  selector:           
    app: traffic
  type: ClusterIP       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: traffic
spec:                
  selector:         
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:        
        app: traffic
    spec:
      containers:
        - name: traffic
          image: vkatkar1998/traffic:latest
          ports:
            - containerPort: 8080
               
        